---
- hosts: elevate
  vars:
    github_repo: "ELEVATE-Project/utils"
    gitBranch: "sprint-5"
    new_version: "1.0.2"
    github_token: "your_token_here"
  tasks:
  - name: Create GitHub Release Tag
    uri:
      url: "https://api.github.com/repos/{{ GIT_REF }}/releases"
      method: POST
      headers:
        Authorization: "Bearer {{ GIT_TOKEN }}"
        Accept: "application/vnd.github+json"
        Content-Type: "application/json"
      body_format: json
      body:
        tag_name: "v{{ new_version }}"
        target_commitish: "{{ gitBranch }}"
        name: "v{{ new_version }}"
        body: "Automated release v{{ new_version }} created by Ansible"
        draft: false
        prerelease: false
      status_code: 201
      delegate_to: localhost
      run_once: true
